travis:
  secure:
    BINSTAR_TOKEN: QSbHTxoPmTnrfNxAseIE9uGNeqfAmDdetg02r5nkHiLdW6HOIoDvV6oZ8iJX7l9/QanUgwdxoLPKh4Bhlhc1RDQ2i0BylGlTq1E8KOjhWBw3U8RYx4DKWf/jLYFf9wwkcdW5/0XqukqscZ4smQkk3IHMTESMln3Up0VWStEYID3UIwiJ3nZbQXBStbU/oYndOsVOHXOTipsCt83VUNQN7WvUGkstix2ycLa0IFCnzVS/LQNdqFxjDP0tqiQBPYSHPMy4xh0lmOSNl4EMcJCi7Pr96SF5FYgJZjqS28+gByXtBO0uadpGJJwLqKDhS73knYBEEs3Pf8rD1jIAREGsECAeM7OTdzNpejlAZXwuEelV70IxBqjnfrzLliHz+/bmsSoFL+MQReC5nU3rpPbVHsYe4GqKq5LOnB+3zJY0cmzwPAfkhg9YGswNDZbNVHYHgHujXAHezyOLe5n+NIz4MUm7pjtpu9Pcw46BqFgk2oG0LBNrS8AT6evdM030+F4MmJcrQrbZjIkhjDu/wJRaI9TOO3ouhVyLSVRbA11tQHiavhktHJcQic1tdqvyr+98Vex4lpAAIGGE2iPhssTlSsTufZ8UtWFZ9PSFbfnGHBopKCfJYXHn3hPDBv7HwXXZyhaFDGB/J0I9dztduzMeJZsHB/rhTN5TyQTO6GxjkHk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
