appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: L23goDvQMsHrGzxUBSavXsZqSo3HXbLrsB0YqEEMoROPzRhD90M+ekNatMVcy58RS3Y+MGLhIpNUwrbK8GRddWLb0N+FSLH/h9z/pDqNO488CtRdFLVm+FXz5RRR9ZGs4WBRXzj+S166qgwzC2ydT8swGZk9F5doWVWH3Ptm5LZzGVGecAJMPAosjqy/jCBOmuMYjJd1GbO40xtNOcfPHEGCnPVkt9GzqmHEO7hsorf70OGv6CF2L1zbH9ewaFuMot5AhLFjJyLVNowveOoyV+vHxNeg9sWrfiYmggw9pApR2h5XP8+Ik4lEr2Gw/zsZL5dfbORfPDlIOkep7R13dmHorTLGiMPM3PnUGO3Ec5QE0ozAT8Wlu4ch+tHB5E5A53BIZpUufjjECpAL1xShA1L5IfogTmdWtZOGaKs8m8RXvs2RSW08cdootLzaBoAdEJ7tk1BD70OcMBQ2as+ZDp+al77FSllpb9H8dFuABNskWogD8LFbhHh2/n+f9nYqKOrFe+Eg9CI9LAYNFBfAxWEiYAhItH0rLeNWqIw3yX871riGxwKnjmeY27O4Uf9mo2eyKYme3zs44LNoYOYDeHrX7xMQoGcKmbS4gjuHK04/3mXtQm7e6jHVkzinFP9o6VtTdvl715+hJ3+DaVQo8s8tuGZbq47yfxBU/F6PPOQ=}
